### PR TITLE
Make it an app

### LINKED ISSUE #20: Converting to an App
Sooooo Apps are a new thing coming and will be way better than integrations are, with the ability to show up as a native implementation. One of the features currently implemented for Apps is commands, which work both on the native mobile applications and on the web. However, one feature which is coming up for Apps very soon is the preview of images, gifs, video, audio, etc. I need an example one to show off the previews, would you mind if I did one based upon your code here? I would even be willing to submit a pull request to add the code here... 

I would probably only add the `/gif` or `/giphy` for right now. Later someone could use what I wrote as an example to implement the `/sticker` or something similar.

### PR DESCRIPTION
**Pull request by graywolf336**
Closes #20 

Okay, so first thing is first. The App code is best done in a folder under the [Development Environment](https://github.com/RocketChat/Rocket.Chat.Apps-dev-environment) as that contains helper items to make Rocket.Chat Apps easier to develop. With that said though, I am committing it here since I used this repository as a base....and the code is not yet completed as there is still lots of i18n strings that could be improved and added.

Another thing to note, this App won't work with versions earlier than v0.65.0-rc.2 of Rocket.Chat. One last thing, the UI for the previews is very ugly and is in the process of being "beautified".

Here is the App package which can be downloaded and installed in your Rocket.Chat. :) [giphy_0.1.2.zip](https://github.com/FinndropStudios/GifRocket/files/2040839/giphy_0.1.2.zip)

### CODE REVIEW

**Comment by graywolf336** [comment]
Oh, and the readme isn't updated...sorry

**Comment by manuelbachl** [comment]
Awesome! Thanks for that improvement! I think I'll get my hands dirty this weekend finilazing your code (with those things you've mentioned above). Looks quite straightforward and not that hard to dive into the code :-)
I'll let you know once updated

**Comment by graywolf336** [comment]
No problem! :)

If you want to dive into the settings feature of Apps, you can think about adding a setting to toggle whether the name of the gif gets appended to the attachment or not.

**Comment by manuelbachl** [comment]
Is there any channel, where I could get in touch with you when any questions occur?

**Comment by graywolf336** [comment]
@manuelbachl best place right now is just a direct message. Hopefully after this week or next we will have a channel and information on there.

**Comment by graywolf336** [comment]
Some ideas for the App:
- [ ] Configurable attachment title
  - [ ] Show the name of the giphy result
  - [ ] Show the search term
  - [ ] Show something like "Posted by <username> using Giphy"?
- [ ] Toggle whether the giphy is posted as the searcher or some other user
- [ ] Setting of whether the attachment color is random
- [ ] Implement the `/sticker` command

**Comment by manuelbachl** [comment]
Looks like a nice feature list :-) maybe I'll should add some kind of a roadmap to this repo

**Comment by manuelbachl** [comment]
Roadmap can be found here:
https://github.com/FinndropStudios/GifRocket/projects/1

**Comment by AlexVonB** [comment]
Hi,
thanks for the app, it works great so far. I'd like to add a point to the roadmap:

- Toggle/disable logging every request into server logs

Thank you!

**Comment by graywolf336** [comment]
@AlexVonB Yes, Apps are extremely verbose right now on the Rocket.Chat side :see_no_evil: it's my fault and the next release they won't be, I promise. :blush:

**Comment by manuelbachl** [comment]
Finally i have some spare time to take a look on this, but that happened: https://github.com/RocketChat/Rocket.Chat.Apps-dev-environment/issues/17

:-D

**Pull request merged**
